[tool.black]
line-length = 100

[tool.isort]
profile = 'black'
skip_gitignore = false
line_length = 100
atomic = true
known_first_party = ["src", "scripts"]
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'LOCALFOLDER', 'FIRSTPARTY']

